# Generated by Django 4.0.3 on 2022-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Enter URL', max_length=10000, verbose_name='URL')),
                ('img_link', models.TextField(verbose_name='Image Link')),
                ('href_link', models.TextField(verbose_name='Web page Link')),
            ],
        ),
    ]
