# Generated by Django 3.0 on 2022-04-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraper',
            options={'ordering': ('-id',)},
        ),
    ]
